// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import (
	domain "arquitetura-go/internal/products/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ProductRepository is an autogenerated mock type for the ProductRepository type
type ProductRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (_m *ProductRepository) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx
func (_m *ProductRepository) GetAll(ctx context.Context) ([]domain.Product, error) {
	ret := _m.Called(ctx)

	var r0 []domain.Product
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Product); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LastID provides a mock function with given fields:
func (_m *ProductRepository) LastID() (int, error) {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, id, name, typee, count, price
func (_m *ProductRepository) Store(ctx context.Context, id int, name string, typee string, count int, price float64) (domain.Product, error) {
	ret := _m.Called(ctx, id, name, typee, count, price)

	var r0 domain.Product
	if rf, ok := ret.Get(0).(func(context.Context, int, string, string, int, float64) domain.Product); ok {
		r0 = rf(ctx, id, name, typee, count, price)
	} else {
		r0 = ret.Get(0).(domain.Product)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, string, string, int, float64) error); ok {
		r1 = rf(ctx, id, name, typee, count, price)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, name, productType, count, price
func (_m *ProductRepository) Update(ctx context.Context, id int, name string, productType string, count int, price float64) (domain.Product, error) {
	ret := _m.Called(ctx, id, name, productType, count, price)

	var r0 domain.Product
	if rf, ok := ret.Get(0).(func(context.Context, int, string, string, int, float64) domain.Product); ok {
		r0 = rf(ctx, id, name, productType, count, price)
	} else {
		r0 = ret.Get(0).(domain.Product)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, string, string, int, float64) error); ok {
		r1 = rf(ctx, id, name, productType, count, price)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateName provides a mock function with given fields: ctx, id, name
func (_m *ProductRepository) UpdateName(ctx context.Context, id int, name string) (domain.Product, error) {
	ret := _m.Called(ctx, id, name)

	var r0 domain.Product
	if rf, ok := ret.Get(0).(func(context.Context, int, string) domain.Product); ok {
		r0 = rf(ctx, id, name)
	} else {
		r0 = ret.Get(0).(domain.Product)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = rf(ctx, id, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type NewProductRepositoryT interface {
	mock.TestingT
	Cleanup(func())
}

// NewProductRepository creates a new instance of ProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProductRepository(t NewProductRepositoryT) *ProductRepository {
	mock := &ProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
