name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Basic tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          go mod download
        run: |
          go test -v -cover ./...